### ISSUE TITLE
Error when using `WeaviateVectorStore.from_documents()`

### ISSUE THREAD

**Issue by StreetLamb** [langchain-ai/langchain-weaviate#177]
**Describe the bug**

I am encountering an error where `moduleConfig` is not present in the schema when running `WeaviateVectorStore.from_documents()`. 
```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Users/xxx/.vscode/extensions/ms-python.debugpy-2024.6.0-darwin-arm64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/Users/xxx/Desktop/projects/xxx/backend/app/core/test.py", line 22, in <module>
    db = WeaviateVectorStore.from_documents(docs, embeddings, client=weaviate_client)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/langchain_core/vectorstores.py", line 550, in from_documents
    return cls.from_texts(texts, embedding, metadatas=metadatas, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/langchain_weaviate/vectorstores.py", line 477, in from_texts
    weaviate_vector_store = cls(
                            ^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/langchain_weaviate/vectorstores.py", line 129, in __init__
    self._multi_tenancy_enabled = self._collection.config.get(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/weaviate/collections/config.py", line 81, in get
    return _collection_config_from_json(schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/weaviate/collections/classes/config_methods.py", line 246, in _collection_config_from_json
    vectorizer_config=__get_vectorizer_config(schema),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/Library/Caches/pypoetry/virtualenvs/app-w4MTL1IK-py3.12/lib/python3.12/site-packages/weaviate/collections/classes/config_methods.py", line 78, in __get_vectorizer_config
    vec_config: Dict[str, Any] = schema["moduleConfig"].pop(schema["vectorizer"])
                                 ~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'moduleConfig'
```
 
**Complete Minimal Reproducible Example**

docker-compose.yml
```
---
version: '3.4'
services:
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.24.10
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      CLIP_INFERENCE_API: 'http://multi2vec-clip:8080'
      RERANKER_INFERENCE_API: 'http://reranker-transformers:8080'
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'
      ENABLE_MODULES: 'multi2vec-clip,reranker-transformers'
      CLUSTER_HOSTNAME: 'node1'
  multi2vec-clip:
    image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
    environment:
      ENABLE_CUDA: '0'
  reranker-transformers:
    image: cr.weaviate.io/semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
    environment:
      ENABLE_CUDA: '0'
volumes:
  weaviate_data:
...
```

I received the error when running the following code:
```py
from langchain.text_splitter import CharacterTextSplitter
from langchain_community.document_loaders import TextLoader
from langchain_openai import OpenAIEmbeddings
import weaviate
from langchain_weaviate.vectorstores import WeaviateVectorStore

OPENAI_API_KEY='xxxx'

loader = TextLoader("state_of_the_union.txt")
documents = loader.load()
text_splitter = CharacterTextSplitter(chunk_size=1000, chunk_overlap=0)
docs = text_splitter.split_documents(documents)

embeddings = OpenAIEmbeddings(api_key=OPENAI_API_KEY)
weaviate_client = weaviate.connect_to_local(port=8080)
db = WeaviateVectorStore.from_documents(docs, embeddings, client=weaviate_client) # error occured here
```

**Expected behavior**
I should be able to create my Weaviate vector store without issues

**Tech Stack (please complete the following information):**
- weaviate server version: 1.24.10
- weaviate modules enabled: 'multi2vec-clip,reranker-transformers'
- langchain-weaviate version: 0.0.1.post1
- langchain version: 0.1.17

**Additional context**
No issues when using weaviate library directly, so probably an issue with how langchain-weaviate creates the initial schema.

**Comment by hsm207** [comment]
what version of the weaviate client do you have installed?

**Comment by StreetLamb** [comment]
Hi @hsm207 , I'm on version 4.5.7

**Comment by hsm207** [comment]
Hi @StreetLamb,

in your docker compose, you have:

> DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'

at the same time, in the code, you are saying you want to use openai for the embeddings:

> embeddings = OpenAIEmbeddings(api_key=OPENAI_API_KEY)
> weaviate_client = weaviate.connect_to_local(port=8080)
> db = WeaviateVectorStore.from_documents(docs, embeddings, client=weaviate_client) 

This is a conflict, since the default schema created by langchain assumes no weaviate modules is being used for vectorization. To remove this error, you need to remove this line from your docker compose file:

> DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip'

If you actually meant to use weaviate's modules to do the vectorization, then the following question arises:

Why use langchain and not just weaviate stand-alone?

This issue has come up often enough that I've made a specific issue to track it to gather community feedback to help understand the intended use case and jointly design an optimal solution. See #95 and feel free to chime in with your thoughts.

**Comment by kihumban** [comment]
I recognized this issue has been closed. I have followed the instruction given above by @hsm207 and removed DEFAULT_VECTORIZER_MODULE: 'multi2vec-clip' from the docker compose file. However, I am still getting **KeyError: 'moduleConfig'** errror message.
